# Generated by Django 3.1.3 on 2021-07-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sic', '0003_auto_20210701_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
