# Generated by Django 3.1.3 on 2021-07-01 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sic', '0007_user_usename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usename',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='banned_by_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='disabled_invite_by_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='github_username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
    ]
