# Generated by Django 3.1.3 on 2021-07-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sic', '0011_auto_20210702_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='accepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
