# Generated by Django 3.1.3 on 2021-07-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sic', '0015_auto_20210702_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='user_is_author',
            field=models.BooleanField(default=False),
        ),
    ]
