# Generated by Django 3.1.3 on 2021-07-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sic', '0016_story_user_is_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='hex_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
