# Generated by Django 3.2.5 on 2021-07-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sic', '0017_tag_hex_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='hex_color',
            field=models.CharField(blank=True, default='#fff', max_length=7, null=True),
        ),
    ]
