# Generated by Django 3.2.5 on 2021-07-04 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sic', '0018_alter_tag_hex_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='sic.comment'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='hex_color',
            field=models.CharField(blank=True, default='#fffff', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='sic.story'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('story__isnull', False), ('comment__isnull', False), _connector='OR'), models.Q(('story__isnull', False), ('comment__isnull', False), _negated=True)), name='not_both_null'),
        ),
    ]
