# Generated by Django 3.2.5 on 2021-07-04 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sic', '0019_auto_20210704_1055'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='not_both_null',
        ),
        migrations.AlterField(
            model_name='vote',
            name='story',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='sic.story'),
            preserve_default=False,
        ),
    ]
