# Generated by Django 3.2.5 on 2021-07-04 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sic', '0020_auto_20210704_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='receiver',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
