# Generated by Django 3.1.3 on 2021-07-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0026_auto_20210706_2207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="commentbookmark",
            unique_together={("comment", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="storybookmark",
            unique_together={("story", "user")},
        ),
    ]
