# Generated by Django 3.1.3 on 2021-07-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0028_story_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
