# Generated by Django 3.1.3 on 2021-07-08 10:04

from django.db import migrations, models
import sic.models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0029_auto_20210708_0959"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryKind",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40, unique=True)),
                (
                    "hex_color",
                    models.CharField(
                        blank=True, default="#fffff", max_length=7, null=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="story",
            name="kind",
            field=models.ManyToManyField(
                default=sic.models.StoryKind.default_value,
                related_name="stories",
                to="sic.StoryKind",
            ),
        ),
    ]
