# Generated by Django 3.1.3 on 2021-07-08 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("sic", "0031_auto_20210708_1222"),
        ("sic", "0032_auto_20210708_1657"),
        ("sic", "0033_taggregation_description"),
    ]

    dependencies = [
        ("sic", "0030_auto_20210708_1004"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taggregation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now_add=True)),
                ("default", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_taggregations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "moderators",
                    models.ManyToManyField(
                        related_name="moderated_taggregations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tags", models.ManyToManyField(to="sic.Tag")),
                ("discoverable", models.BooleanField(default=False)),
                ("private", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="taggregation_subscriptions",
            field=models.ManyToManyField(blank=True, to="sic.Taggregation"),
        ),
    ]
