# Generated by Django 3.1.3 on 2021-07-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0035_auto_20210711_1812"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_mentions",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_messages",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_replies",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_story_previews",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_submitted_story_threads",
            field=models.BooleanField(default=True),
        ),
    ]
