# Generated by Django 3.1.3 on 2021-07-12 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [("sic", "0037_notification"), ("sic", "0038_notification_body")]

    dependencies = [
        ("sic", "0036_auto_20210711_1828"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("RE", "New reply"),
                            ("MSG", "New message"),
                            ("MODR", "A moderator acted on your behalf"),
                            ("OTHR", "New notification"),
                        ],
                        default="OTHR",
                        max_length=4,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "caused_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("body", models.TextField(blank=True)),
            ],
        ),
    ]
