# Generated by Django 3.1.3 on 2021-07-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0037_notification_squashed_0038_notification_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="metadata_1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="metadata_1_label",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="metadata_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="metadata_2_label",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="metadata_3",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="metadata_3_label",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="metadata_4",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="metadata_4_label",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
