# Generated by Django 3.1.3 on 2021-07-13 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0038_auto_20210713_1216"),
    ]

    operations = [
        migrations.AddField(
            model_name="hat",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hat",
            name="hex_color",
            field=models.CharField(
                blank=True, default="#000000", max_length=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="hat",
            name="last_modified",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hat",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
