# Generated by Django 3.1.3 on 2021-07-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0040_auto_20210714_2159"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_colors",
            field=models.BooleanField(default=True),
        ),
    ]
