# Generated by Django 3.1.3 on 2021-07-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0041_user_show_colors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={"verbose_name_plural": "stories"},
        ),
    ]
