# Generated by Django 3.1.3 on 2021-07-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0042_auto_20210715_1309"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="taggregation_subscriptions",
            field=models.ManyToManyField(
                blank=True, related_name="subscribers", to="sic.Taggregation"
            ),
        ),
    ]
