# Generated by Django 3.1.3 on 2021-07-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0043_auto_20210716_0746"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
