# Generated by Django 3.1.3 on 2021-07-17 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("sic", "0044_user_auth_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationLogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField(auto_now_add=True)),
                ("action", models.TextField()),
                ("reason", models.TextField()),
                ("change", models.TextField(blank=True, null=True)),
                (
                    "object_id",
                    models.TextField(blank=True, null=True, verbose_name="object id"),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("change_is_public", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "moderation log entry",
                "verbose_name_plural": "moderation log entries",
                "ordering": ["-action_time"],
            },
        ),
    ]
