# Generated by Django 3.1.3 on 2021-07-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0045_moderationlogentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderationlogentry",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
