# Generated by Django 3.1.3 on 2021-07-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0047_with_cte_tag_view"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storykind",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="taggregation",
            options={"ordering": ["name"]},
        ),
    ]
