# Generated by Django 3.1.3 on 2021-07-21 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0048_auto_20210718_1641"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webmention",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.URLField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("was_received", models.BooleanField(default=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webmentions",
                        to="sic.story",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "story"],
            },
        ),
    ]
