# Generated by Django 3.1.3 on 2021-07-19 06:25

from django.db import migrations, models
import django.db.models.deletion


def create_through_relations(apps, schema_editor):
    Taggregation = apps.get_model("sic", "Taggregation")
    TaggregationHasTag = apps.get_model("sic", "TaggregationHasTag")
    for tagg in Taggregation.objects.all():
        for tag in tagg.tags.all():
            TaggregationHasTag(
                taggregation=tagg,
                tag=tag,
            ).save()


def remove_through_relations(apps, schema_editor):
    TaggregationHasTag = apps.get_model("sic", "TaggregationHasTag")
    TaggregationHasTag.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0051_add_unique_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaggregationHasTag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sic.tag",
                    ),
                ),
                (
                    "taggregation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sic.taggregation",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            code=create_through_relations,
            reverse_code=remove_through_relations,
        ),
        migrations.RemoveField(
            model_name="taggregation",
            name="tags",
        ),
        migrations.AddField(
            model_name="taggregation",
            name="tags",
            field=models.ManyToManyField(
                related_name="taggregations",
                through="sic.TaggregationHasTag",
                to="sic.Tag",
            ),
        ),
    ]
