# Generated by Django 3.1.3 on 2021-07-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0052_taggregationhastag_through_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="taggregationhastag",
            name="depth",
            field=models.IntegerField(default=0),
        ),
    ]
