# Generated by Django 3.1.3 on 2021-07-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sic', '0054_add_story_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='positive',
            field=models.BooleanField(default=True),
        ),
    ]
