# Generated by Django 3.1.3 on 2021-07-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0054_add_story_filters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taggregationhastag",
            name="include_filters",
        ),
    ]
