# Generated by Django 3.1.3 on 2021-07-30 09:23

from django.db import migrations, models


def change_depth(apps, schema_editor):
    TaggregationHasTag = apps.get_model("sic", "TaggregationHasTag")
    TaggregationHasTag.objects.filter(depth=-1).update(depth=0)


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0055_remove_taggregationhastag_include_filters"),
    ]

    operations = [
        migrations.RunPython(change_depth, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="taggregationhastag",
            name="depth",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
