# Generated by Django 3.1.3 on 2021-08-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0056_make_depth_field_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="context_warning",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="show_stories_with_context_warning",
            field=models.BooleanField(default=True),
        ),
    ]
