# Generated by Django 3.1.3 on 2021-08-03 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sic', '0058_digest'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryRemoteContent',
            fields=[
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='remote_content', serialize=False, to='sic.story')),
                ('url', models.URLField()),
                ('content', models.TextField()),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
