# Generated by Django 3.1.3 on 2021-08-04 14:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sic", "0059_storyremotecontent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="id",
        ),
        migrations.AlterField(
            model_name="domain",
            name="url",
            field=models.URLField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="domain",
            name="url",
            field=models.URLField(
                primary_key=True,
                serialize=False,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="domain",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sic.domain",
            ),
        ),
    ]
