# Generated by Django 3.1.3 on 2021-08-05 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0061_add_last_modified_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="last_active",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
