# Generated by Django 3.1.3 on 2021-08-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0062_story_last_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="active",
        ),
        migrations.AddField(
            model_name="notification",
            name="read",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
