# Generated by Django 3.1.3 on 2021-08-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0063_add_read_datetime_field_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitationrequest",
            name="fulfilled_by",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="request",
                to="sic.invitation",
            ),
        ),
    ]
