# Generated by Django 3.1.3 on 2021-08-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0064_invitationrequest_fulfilled_by"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    "CREATE INDEX story_votes ON sic_vote(story_id) WHERE comment_id IS NULL;",
                    [],
                )
            ],
            reverse_sql=[("DROP INDEX story_votes;", [])],
        ),
        migrations.RunSQL(
            sql=[
                ("CREATE INDEX story_active ON sic_story(id) WHERE active IS TRUE;", [])
            ],
            reverse_sql=[("DROP INDEX story_active;", [])],
        ),
        migrations.RunSQL(
            sql=[("CREATE INDEX story_title ON sic_story(title);", [])],
            reverse_sql=[("DROP INDEX story_title;", [])],
        ),
        migrations.RunSQL(
            sql=[("CREATE INDEX story_created ON sic_story(created);", [])],
            reverse_sql=[("DROP INDEX story_created;", [])],
        ),
    ]
