# Generated by Django 3.1.3 on 2021-08-14 15:11

from django.db import migrations
from sic.apps import SicAppConfig as config


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0067_create_lastmodified_triggers"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    f"""CREATE VIRTUAL TABLE IF NOT EXISTS {config.MENTION_TOKENIZER_NAME} USING fts3tokenize('unicode61');""",
                    [],
                )
            ],
            reverse_sql=[(f"DROP TABLE {config.MENTION_TOKENIZER_NAME};", [])],
        ),
    ]
