# Generated by Django 3.1.3 on 2021-08-14 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0068_create_mention_tokenizer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="story",
            old_name="context_warning",
            new_name="content_warning",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="show_stories_with_context_warning",
            new_name="show_stories_with_content_warning",
        ),
    ]
