# Generated by Django 3.1.3 on 2021-08-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0069_rename_context_warning_to_content_warning"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("PRAGMA legacy_alter_table = TRUE;", []),
            ],
            reverse_sql=[("PRAGMA legacy_alter_table = TRUE;", [])],
        ),
        migrations.AddField(
            model_name="story",
            name="karma",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.RunSQL(
            sql=[
                (
                    """CREATE TRIGGER sic_vote_insert AFTER INSERT ON sic_vote
                    FOR EACH ROW WHEN NEW.comment_id IS NULL
                    BEGIN
                    UPDATE sic_story
                    SET karma = (karma + 1)
                    WHERE
                        id = NEW.story_id;
                        END;""",
                    [],
                )
            ],
            reverse_sql=[("DROP TRIGGER IF EXISTS sic_vote_insert", [])],
        ),
        migrations.RunSQL(
            sql=[
                (
                    """CREATE TRIGGER sic_vote_delete AFTER DELETE ON sic_vote
                    FOR EACH ROW WHEN OLD.comment_id IS NULL
                    BEGIN
                    UPDATE sic_story
                    SET karma = (karma - 1)
                    WHERE
                        id = OLD.story_id;
                        END;""",
                    [],
                )
            ],
            reverse_sql=[("DROP TRIGGER IF EXISTS sic_vote_delete", [])],
        ),
        migrations.RunSQL(
            sql=[
                (
                    """UPDATE sic_story SET karma = (SELECT COUNT(id) FROM sic_vote AS v WHERE v.story_id = sic_story.id AND v.comment_id IS NULL);""",
                    [],
                )
            ],
            reverse_sql=[("", [])],
        ),
        migrations.AddField(
            model_name="comment",
            name="karma",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.RunSQL(
            sql=[
                (
                    """CREATE TRIGGER sic_vote_insert_comment AFTER INSERT ON sic_vote
                    FOR EACH ROW WHEN NEW.comment_id IS NOT NULL
                    BEGIN
                    UPDATE sic_comment
                    SET karma = (karma + 1)
                    WHERE
                        id = NEW.comment_id;
                        END;""",
                    [],
                )
            ],
            reverse_sql=[("DROP TRIGGER IF EXISTS sic_vote_insert_comment", [])],
        ),
        migrations.RunSQL(
            sql=[
                (
                    """CREATE TRIGGER sic_vote_delete_comment AFTER DELETE ON sic_vote
                    FOR EACH ROW WHEN OLD.comment_id IS NOT NULL
                    BEGIN
                    UPDATE sic_comment
                    SET karma = (karma - 1)
                    WHERE
                        id = OLD.comment_id;
                        END;""",
                    [],
                )
            ],
            reverse_sql=[("DROP TRIGGER IF EXISTS sic_vote_delete_comment", [])],
        ),
        migrations.RunSQL(
            sql=[
                (
                    """UPDATE sic_comment SET karma = (SELECT COUNT(id) FROM sic_vote AS v WHERE v.story_id = sic_comment.story_id AND v.comment_id = sic_comment.id);""",
                    [],
                )
            ],
            reverse_sql=[("", [])],
        ),
        migrations.RunSQL(
            sql=[
                ("PRAGMA legacy_alter_table = TRUE;", []),
            ],
            reverse_sql=[("PRAGMA legacy_alter_table = TRUE;", [])],
        ),
    ]
