# Generated by Django 3.2.6 on 2021-08-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0071_job_jobkind"),
    ]

    operations = [
        migrations.AddField(
            model_name="webmention",
            name="source",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="webmention",
            name="target",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
