# Generated by Django 3.1.3 on 2021-08-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0073_show_path_in_tag_cycle_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="exclude_filters",
            field=models.ManyToManyField(
                blank=True, related_name="excluded_in_user", to="sic.StoryFilter"
            ),
        ),
    ]
