# Generated by Django 3.2.6 on 2021-08-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0075_add_message_id_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="enable_mailing_list",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="enable_mailing_list_comments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="enable_mailing_list_replies",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="enable_mailing_list_replying",
            field=models.BooleanField(default=False),
        ),
    ]
