# Generated by Django 3.2.6 on 2021-08-29 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0076_add_mailing_list_user_options"),
        ("flatpages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityFlatPage",
            fields=[
                (
                    "flatpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flatpages.flatpage",
                    ),
                ),
                ("link_name", models.TextField(null=True)),
                ("show_inline", models.BooleanField(blank=True, default=False)),
                ("show_in_footer", models.BooleanField(blank=True, default=False)),
                (
                    "order",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
            ],
            bases=("flatpages.flatpage",),
        ),
        migrations.CreateModel(
            name="DocumentationFlatPage",
            fields=[
                (
                    "flatpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flatpages.flatpage",
                    ),
                ),
                ("link_name", models.TextField(null=True)),
                ("show_in_footer", models.BooleanField(blank=True, default=False)),
                (
                    "order",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
            ],
            bases=("flatpages.flatpage",),
        ),
        migrations.CreateModel(
            name="ExternalLinkFlatPage",
            fields=[
                (
                    "flatpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flatpages.flatpage",
                    ),
                ),
                ("link_name", models.TextField()),
                ("external_url", models.URLField()),
                ("show_inline", models.BooleanField(blank=True, default=False)),
                ("show_in_footer", models.BooleanField(blank=True, default=False)),
                (
                    "order",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
            ],
            bases=("flatpages.flatpage",),
        ),
    ]
