# Generated by Django 3.2.6 on 2021-08-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0077_communityflatpage_documentationflatpage_externallinkflatpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityflatpage",
            name="show_in_header",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="documentationflatpage",
            name="show_in_header",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="externallinkflatpage",
            name="show_in_header",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
