# Generated by Django 3.2.6 on 2021-08-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0078_add_show_in_header_to_flatpages"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityflatpage",
            name="show_in_about",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="Show in about page"
            ),
        ),
        migrations.AddField(
            model_name="documentationflatpage",
            name="show_in_about",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="Show in about page"
            ),
        ),
        migrations.AddField(
            model_name="externallinkflatpage",
            name="show_in_about",
            field=models.BooleanField(
                blank=True, default=True, verbose_name="Show in about page"
            ),
        ),
    ]
