# Generated by Django 3.2.6 on 2021-09-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0080_user_email_validated"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
    ]
