# Generated by Django 3.2.6 on 2021-09-11 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0082_storyremotecontent_w3m_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitationrequest",
            name="requested_by",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invitation_request",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
