# Generated by Django 3.2.6 on 2021-11-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0083_invitationrequest_requested_by"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE sic_story ADD COLUMN 'pinned' datetime NULL;",
            reverse_sql=";",
            state_operations=[
                migrations.AddField(
                    model_name="story",
                    name="pinned",
                    field=models.DateTimeField(blank=True, default=None, null=True),
                ),
            ],
        ),
        migrations.RunSQL(
            sql=";",
            reverse_sql=";",
            state_operations=[
                migrations.AlterField(
                    model_name="story",
                    name="content_warning",
                    field=models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
        ),
    ]
