# Generated by Django 3.2.6 on 2021-11-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0084_story_pinned"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taggregation",
            options={
                "ordering": ["name"],
                "verbose_name": "aggregation",
                "verbose_name_plural": "aggregations",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="ssh_public_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
