# Generated by Django 3.2.6 on 2021-11-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0085_add_ssh_public_key_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_on_new_invitation_request",
            field=models.BooleanField(default=False),
        ),
    ]
