# Generated by Django 3.2.20 on 2023-07-17 08:17

from django.db import migrations, models

import importlib.util
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location(
    "migrate_story_triggers", BASE_DIR / ".migrate_story_triggers.py"
)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
sys.modules["migrate_story_triggers"] = module

from migrate_story_triggers import CREATES, DROPS


class Migration(migrations.Migration):
    dependencies = [
        ("sic", "0086_user_notify_on_new_invitation_request"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DROPS,
            reverse_sql=CREATES,
        ),
        migrations.AddField(
            model_name="story",
            name="requires_javascript",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            sql=CREATES,
            reverse_sql=DROPS,
        ),
    ]
